version: "3.9"

# just to show I worked on that. That is not being used for running

services:

  app:
    build: .
    depends_on:
      - database
    container_name: app_apiports

  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - app_data:/data/db


volumes:
  app_data: