version: "3.9"

services:

  app:
    build: .
    depends_on:
      - database
    container_name: app_apiports
    volumes:
      - ./assets/ports.json:/app/assets/ports.json
    ports:
      - "8080:8080"

  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - app_data:/data/db
    ports:
      - "27017:27017"

volumes:
  app_data: