version: "3.9"

services:

  app:
    build: .
    depends_on:
      - database
    container_name: app_apiports
    volumes:
      - ./assets/ports.json:/app/assets/ports.json

  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - app_data:/data/db


volumes:
  app_data: